[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 88
indent-width = 4

# Check if code is complaint with oldest provided Python
target-version = "py38"

# No point in using this if we don't fix things magically
fix = true

[tool.ruff.lint]
select = [
    "F",  # pyflake linting
    "E",  # Python code style enforced
    "W",  # Ditto, but a lot more nitpicky.
    "I",  # Love Isort.
    "D1",   # Python documentation stuff
    "D414",
    "D417",
    "D418",
    "D419",
    "ASYNC",  # Async gang
    "S1",  # Prevent bad practices with passwords and try excepts
    "Q",  # conform to quotes 
    "RET",  # Flake8 return
    "SIM",  # Write simpler Pythonic code.
    "ARG",  # Detect unused arguments
    "PTH",  # No more os module.  
    "PL",   # Pylint has good rules.
    "RUF",  # Goated RUFF rules.
]


# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
